### ISSUE TITLE
Any chance of an executable please? I get build errors when I try to run this

### ISSUE THREAD

**Issue by jiraffe1** [carl-vbn/opengl-gravity-simulator#1]

**Comment by carl-vbn** [comment]
I will see if I can upload an executable, but you could you detail the errors you are getting?

**Comment by jiraffe1** [comment]
VS says that it cannot open the file glfw3.lib, I think this is an issue with compatibility or something like that

**Comment by carl-vbn** [comment]
Okay I figured out what the problem was. The gitignore file contained *.lib which is why glfw3.lib was missing from your local repository. I've also pushed a Release build available inside the Release folder, but it depends on the "shaders" and "fonts" folders located there so it won't work if you move it. Could you try building again and running the released executable and let me know if it works? Thanks

**Comment by jiraffe1** [comment]
Ok thanks! Everything builds and runs fine now and works perfectly :D

**Comment by Genious28** [comment]
Hey, i've decided to use your project as a base engine, and I'm gonna add General Relativity and maybe even BlackHoles. But the problem is, i can't run the Project. 
I'm used to VSCode and never used VSProfessional. Though, i did install VSPro just for the sake of the project but i still can't make it execute.. It's just not identifying the Include Folders and Libraries. I tried many OpenGL VSPro Setup Guides online but none worked.
Can you please help me out with porting it to VSCode or at least with the Project Configurations within VSPro? I will be submitting the forked build as a Project for my University Course in 2 days.

**Comment by Genious28** [comment]
Hey @carl-vbn, i've decided to use your project as a base engine, and I'm gonna add General Relativity and maybe even BlackHoles. But the problem is, i can't run the Project. 
I'm used to VSCode and never used VSProfessional. Though, i did install VSPro just for the sake of the project but i still can't make it execute.. It's just not identifying the Include Folders and Libraries. I tried many OpenGL VSPro Setup Guides online but none worked with your file Structure. Also, i am using VSPro 2022.
Can you please help me out with porting it to VSCode or at least with the Project Configurations within VSPro? I will be submitting the forked build as a Project for my University Course in 2 days.

**Comment by Genious28** [comment]
If possible, can you please provide a hidden folder named ".vs" within the project root.. That usually contains all the configurations for a VSPro Project.

**Comment by carl-vbn** [comment]
Hey, sorry about the late reply but unfortunately I cannot provide special support for this project as it was just an experimental project I worked on a few years ago. The source code is provided as is and comes with no support.

**Comment by Genious28** [comment]
> Hey, sorry about the late reply but unfortunately I cannot provide special support for this project as it was just an experimental project I worked on a few years ago. The source code is provided as is and comes with no support.

Understood
